apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-mvc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-mvc-app
  template:
    metadata:
      labels:
        app: dotnet-mvc-app
    spec:
      containers:
        - name: dotnet-mvc-app
          image: "chidiajiboeze1.azurecr.io/dotnet-mvc-app:v1.0.0"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsNonRoot: true
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dotnet-mvc-app
              topologyKey: "kubernetes.io/hostname"








